#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────
//  build-srd.mjs — regenerates js/dnd/data/*.js from the open
//  5e SRD database (https://github.com/5e-bits/5e-database).
//
//  Usage:
//    git clone --depth 1 https://github.com/5e-bits/5e-database /tmp/5edb
//    SRD_DIR=/tmp/5edb/src/2014/en node tools/build-srd.mjs
//
//  The generated files are COMMITTED — players' browsers load
//  them directly; this script only runs when refreshing data.
//
//  Content: SRD 5.1, © Wizards of the Coast LLC, licensed via
//  Creative Commons Attribution 4.0 (CC-BY-4.0).
// ─────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRD = process.env.SRD_DIR;
if (!SRD) { console.error("Set SRD_DIR to the 5e-database src/2014/en folder"); process.exit(1); }
const OUT = join(ROOT, "js", "dnd", "data");
mkdirSync(OUT, { recursive: true });

const load = (name) => JSON.parse(readFileSync(join(SRD, `5e-SRD-${name}.json`), "utf8"));

const HEADER = `// GENERATED by tools/build-srd.mjs — do not edit by hand.
// Content from SRD 5.1 © Wizards of the Coast LLC,
// licensed under CC-BY-4.0 (creativecommons.org/licenses/by/4.0).
`;

// Stable, compact-ish JSON so diffs stay reviewable.
const emit = (file, exports) => {
  let src = HEADER;
  for (const [name, value] of Object.entries(exports)) {
    src += `export const ${name} = ${JSON.stringify(value, null, 1)};\n`;
  }
  writeFileSync(join(OUT, file), src);
  console.log(`  ${file}  ${(src.length / 1024).toFixed(0)} KB`);
};

const byIndex = (arr) => Object.fromEntries(arr.map((x) => [x.index, x]));
const sortByName = (a, b) => a.name.localeCompare(b.name);

/* ═══ core.js — abilities, skills, languages, misc ═══ */
const abilityScores = load("Ability-Scores");
const skills = load("Skills");
const alignments = load("Alignments");
const languages = load("Languages");
const schools = load("Magic-Schools");
const weaponProps = load("Weapon-Properties");
const conditions = load("Conditions");
const proficiencies = byIndex(load("Proficiencies"));

emit("core.js", {
  ABILITIES: ["str", "dex", "con", "int", "wis", "cha"],
  ABILITY_NAMES: Object.fromEntries(abilityScores.map((a) => [a.index, a.full_name])),
  SKILLS: Object.fromEntries(
    skills.sort(sortByName).map((s) => [s.index, { name: s.name, ability: s.ability_score.index }])
  ),
  ALIGNMENTS: alignments.map((a) => ({ index: a.index, name: a.name, abbr: a.abbreviation })),
  LANGUAGES: languages.sort(sortByName).map((l) => ({ index: l.index, name: l.name, type: l.type })),
  SCHOOLS: Object.fromEntries(schools.map((s) => [s.index, s.name])),
  WEAPON_PROPERTIES: Object.fromEntries(
    weaponProps.map((p) => [p.index, { name: p.name, desc: (p.desc || []).join("\n") }])
  ),
  CONDITIONS: Object.fromEntries(
    conditions.map((c) => [c.index, { name: c.name, desc: (c.desc || []).join("\n") }])
  ),
});

/* ═══ helpers for option blobs ═══ */

// {choose, from:{options:[...]}} where options reference abilities
const abilityOptions = (o) =>
  o
    ? { choose: o.choose, bonus: o.from.options[0]?.bonus ?? 1, from: o.from.options.map((x) => x.ability_score.index) }
    : null;

// proficiency reference → {kind, index, name}
function profInfo(ref) {
  const p = proficiencies[ref.index] || { type: "Other", name: ref.name };
  if (ref.index.startsWith("skill-")) return { kind: "skill", index: ref.index.slice(6), name: p.name.replace(/^Skill: /, "") };
  const kind =
    p.type === "Armor" ? "armor" :
    p.type === "Weapons" ? "weapon" :
    p.type === "Saving Throws" ? "save" : "tool";
  return { kind, index: ref.index, name: p.name };
}

// splits a proficiency list into buckets
function profBuckets(list) {
  const out = { skills: [], armor: [], weapons: [], tools: [] };
  (list || []).forEach((ref) => {
    const p = profInfo(ref);
    if (p.kind === "skill") out.skills.push(p.index);
    else if (p.kind === "armor") out.armor.push(p.name);
    else if (p.kind === "weapon") out.weapons.push(p.name);
    else if (p.kind === "tool") out.tools.push(p.name);
  });
  return out;
}

// a proficiency choice → {choose, desc, skills:[...]|null, names:[...]}
function profChoice(c) {
  if (!c) return null;
  const opts = (c.from?.options || []).map((o) => o.item || o).filter((o) => o.index);
  const infos = opts.map(profInfo);
  const allSkills = infos.length > 0 && infos.every((i) => i.kind === "skill");
  return {
    choose: c.choose,
    desc: c.desc || "",
    skills: allSkills ? infos.map((i) => i.index) : null,
    names: allSkills ? null : infos.map((i) => i.name),
  };
}

/* ═══ races.js ═══ */
const traits = byIndex(load("Traits"));
const subracesRaw = load("Subraces");
const racesRaw = load("Races");

const traitDesc = (idx) => (traits[idx]?.desc || []).join("\n\n");

// Dragonborn draconic ancestry subtraits carry breath-weapon info.
const ANCESTRIES = Object.values(traits)
  .filter((t) => t.parent?.index === "draconic-ancestry")
  .map((t) => {
    const ts = t.trait_specific || {};
    return {
      index: t.index.replace("draconic-ancestry-", ""),
      name: t.name.replace("Draconic Ancestry (", "").replace(")", ""),
      damageType: ts.damage_type?.name || "",
      breath: ts.breath_weapon
        ? `${ts.breath_weapon.area_of_effect?.size ?? ""}-ft. ${ts.breath_weapon.area_of_effect?.type ?? ""}, ${ts.breath_weapon.dc?.dc_type?.name ?? ""} save`
        : "",
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

// Racial proficiencies/choices live on the TRAITS (Keen Senses →
// Perception, Dwarven Combat Training → axes…), so aggregate them.
function traitGrants(traitRefs) {
  const skills = [], profs = [], options = [];
  let extraLanguages = 0;
  for (const ref of traitRefs) {
    const t = traits[ref.index];
    if (!t) continue;
    const buckets = profBuckets(t.proficiencies);
    skills.push(...buckets.skills);
    profs.push(...buckets.armor, ...buckets.weapons, ...buckets.tools);
    if (t.proficiency_choices) {
      const pc = profChoice(t.proficiency_choices);
      if (pc) options.push({ ...pc, trait: t.name });
    }
    if (t.language_options) extraLanguages += t.language_options.choose;
  }
  return { skills, profs, options, extraLanguages };
}

const RACES = {};
for (const r of racesRaw) {
  const bonuses = {};
  r.ability_bonuses.forEach((b) => (bonuses[b.ability_score.index] = b.bonus));
  const grants = traitGrants(r.traits);
  RACES[r.index] = {
    index: r.index,
    name: r.name,
    speed: r.speed,
    size: r.size,
    abilityBonuses: bonuses,
    abilityBonusOptions: abilityOptions(r.ability_bonus_options),
    alignment: r.alignment,
    age: r.age,
    sizeDesc: r.size_description,
    languages: r.languages.map((l) => l.index),
    languageOptions: r.language_options
      ? { choose: r.language_options.choose, from: r.language_options.from.options.map((o) => o.item.index) }
      : grants.extraLanguages
        ? { choose: grants.extraLanguages, from: null }
        : null,
    languageDesc: r.language_desc,
    profSkills: grants.skills,
    profs: grants.profs,
    profOptions: grants.options,
    traits: r.traits
      .filter((t) => !t.index.startsWith("draconic-ancestry"))
      .map((t) => ({ index: t.index, name: t.name, desc: traitDesc(t.index) })),
    ancestryOptions: r.index === "dragonborn" ? ANCESTRIES : null,
    subraces: subracesRaw
      .filter((s) => s.race.index === r.index)
      .map((s) => {
        const sb = {};
        s.ability_bonuses.forEach((b) => (sb[b.ability_score.index] = b.bonus));
        const sg = traitGrants(s.racial_traits);
        const sbk = profBuckets(s.starting_proficiencies);
        return {
          index: s.index,
          name: s.name,
          desc: s.desc,
          abilityBonuses: sb,
          profSkills: [...sbk.skills, ...sg.skills],
          profs: [...sbk.armor, ...sbk.weapons, ...sbk.tools, ...sg.profs],
          profOptions: sg.options,
          languages: (s.languages || []).map((l) => l.index),
          languageOptions: s.language_options
            ? { choose: s.language_options.choose, from: null }
            : sg.extraLanguages
              ? { choose: sg.extraLanguages, from: null }
              : null,
          traits: s.racial_traits.map((t) => ({ index: t.index, name: t.name, desc: traitDesc(t.index) })),
          // High elf: one wizard cantrip (INT).
          cantripChoice: s.racial_traits.some((t) => t.index === "high-elf-cantrip")
            ? { class: "wizard", choose: 1, ability: "int" }
            : null,
        };
      }),
    // Tiefling Infernal Legacy — innate spells (SRD).
    racialSpells:
      r.index === "tiefling"
        ? [
            { spell: "thaumaturgy", atLevel: 1, note: "at will", ability: "cha" },
            { spell: "hellish-rebuke", atLevel: 3, note: "2nd level; once per long rest", ability: "cha" },
            { spell: "darkness", atLevel: 5, note: "once per long rest", ability: "cha" },
          ]
        : null,
  };
}
emit("races.js", { RACES });

/* ═══ classes.js ═══ */
const classesRaw = load("Classes");
const subclassesRaw = byIndex(load("Subclasses"));
const levelsRaw = load("Levels");
const featuresRaw = load("Features");

const SPELL_KIND = {
  bard: "known", cleric: "prepared-list", druid: "prepared-list", paladin: "prepared-list",
  ranger: "known", sorcerer: "known", warlock: "pact", wizard: "prepared-book",
};
const RITUAL_CASTER = { bard: true, cleric: true, druid: true, wizard: true };
const SUBCLASS_LEVEL = {
  barbarian: 3, bard: 3, cleric: 1, druid: 2, fighter: 3, monk: 3,
  paladin: 3, ranger: 3, rogue: 3, sorcerer: 1, warlock: 1, wizard: 2,
};

// starting equipment options → readable strings + a resolvable "quick kit" pick
function equipOptionDesc(group) {
  return group.desc || "";
}
function firstResolvable(group) {
  // walk the option tree for the first plain counted_reference(s)
  const out = [];
  const walk = (o) => {
    if (!o) return false;
    if (o.option_type === "counted_reference" && o.of) {
      out.push({ item: o.of.index, name: o.of.name, qty: o.count || 1 });
      return true;
    }
    if (o.option_type === "multiple" && o.items) {
      const picked = o.items.map((i) => walk(i));
      return picked.some(Boolean);
    }
    return false; // equipment_category choices need a human
  };
  const options = group.from?.options || [];
  for (const o of options) if (walk(o)) return out;
  return out;
}

const CLASSES = {};
for (const c of classesRaw) {
  const buckets = profBuckets(c.proficiencies);
  const skillChoice = profChoice(c.proficiency_choices?.find((pc) => profChoice(pc)?.skills));
  const otherChoices = (c.proficiency_choices || [])
    .map(profChoice)
    .filter((pc) => pc && !pc.skills);

  const lvls = levelsRaw
    .filter((l) => l.class.index === c.index && !l.subclass)
    .sort((a, b) => a.level - b.level);

  let prevAsi = 0;
  const levels = lvls.map((l) => {
    const sc = l.spellcasting;
    const slots = sc
      ? [1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => sc[`spell_slots_level_${n}`] || 0)
      : null;
    const asi = (l.ability_score_bonuses || 0) > prevAsi;
    prevAsi = l.ability_score_bonuses || 0;
    return {
      level: l.level,
      profBonus: l.prof_bonus,
      asi,
      features: (l.features || []).map((f) => ({ index: f.index, name: f.name })),
      slots,
      cantrips: sc?.cantrips_known ?? null,
      spellsKnown: sc?.spells_known ?? null,
      classSpecific: l.class_specific || null,
    };
  });

  const subs = (c.subclasses || []).map((ref) => {
    const s = subclassesRaw[ref.index];
    const feats = levelsRaw
      .filter((l) => l.subclass?.index === s.index)
      .sort((a, b) => a.level - b.level)
      .flatMap((l) => (l.features || []).map((f) => ({ index: f.index, name: f.name, level: l.level })));
    return { index: s.index, name: s.name, flavor: s.subclass_flavor, desc: (s.desc || []).join("\n\n"), features: feats };
  });

  const quickKit = [
    ...(c.starting_equipment || []).map((e) => ({ item: e.equipment.index, name: e.equipment.name, qty: e.quantity })),
    ...(c.starting_equipment_options || []).flatMap(firstResolvable),
  ];

  CLASSES[c.index] = {
    index: c.index,
    name: c.name,
    hitDie: c.hit_die,
    saves: c.saving_throws.map((s) => s.index),
    profArmor: buckets.armor,
    profWeapons: buckets.weapons,
    profTools: buckets.tools,
    skillChoices: skillChoice,
    otherProfChoices: otherChoices,
    startEquipOptions: (c.starting_equipment_options || []).map(equipOptionDesc),
    quickKit,
    spell: c.spellcasting
      ? {
          ability: c.spellcasting.spellcasting_ability.index,
          startLevel: c.spellcasting.level,
          kind: SPELL_KIND[c.index] || "known",
          ritual: !!RITUAL_CASTER[c.index],
        }
      : null,
    subclassLevel: SUBCLASS_LEVEL[c.index],
    subclassFlavor: subs[0]?.flavor || "",
    subclasses: subs,
    levels,
    multiclass: {
      prereqs: (c.multi_classing?.prerequisites || []).map((p) => ({ ability: p.ability_score.index, min: p.minimum_score })),
    },
  };
}
emit("classes.js", { CLASSES });

/* ═══ features.js — full feature text, lazily imported ═══ */
const FEATURE_TEXTS = {};
featuresRaw.forEach((f) => {
  FEATURE_TEXTS[f.index] = { name: f.name, desc: (f.desc || []).join("\n\n") };
});
emit("features.js", { FEATURE_TEXTS });

/* ═══ spells.js + spell-texts.js ═══ */
const spellsRaw = load("Spells");
const SPELLS = {};
const SPELL_TEXTS = {};
for (const s of spellsRaw.sort(sortByName)) {
  // damage comes as an array of components (flame strike = fire + radiant)
  const dmgArr = Array.isArray(s.damage) ? s.damage : s.damage ? [s.damage] : [];
  const d0 = dmgArr[0];
  const dmg = d0
    ? {
        type: d0.damage_type?.index || null,
        types: dmgArr.length > 1 ? dmgArr.map((d) => d.damage_type?.index).filter(Boolean) : null,
        atSlot: d0.damage_at_slot_level || null,
        atChar: d0.damage_at_character_level || null,
        // second component (same slot keys) for flame-strike-style spells
        second: dmgArr[1]
          ? { type: dmgArr[1].damage_type?.index || null, atSlot: dmgArr[1].damage_at_slot_level || null }
          : null,
      }
    : null;
  SPELLS[s.index] = {
    index: s.index,
    name: s.name,
    level: s.level,
    school: s.school.index,
    classes: s.classes.map((c) => c.index),
    time: s.casting_time,
    range: s.range,
    components: (s.components || []).join(", "),
    duration: s.duration,
    concentration: !!s.concentration,
    ritual: !!s.ritual,
    attack: s.attack_type || null,
    dc: s.dc ? { ability: s.dc.dc_type.index, success: s.dc.dc_success } : null,
    damage: dmg,
    heal: s.heal_at_slot_level ? { atSlot: s.heal_at_slot_level } : null,
    aoe: s.area_of_effect ? { type: s.area_of_effect.type, size: s.area_of_effect.size } : null,
  };
  SPELL_TEXTS[s.index] = {
    desc: (s.desc || []).join("\n\n"),
    higher: (s.higher_level || []).join("\n\n"),
    material: s.material || "",
  };
}
emit("spells.js", { SPELLS });
emit("spell-texts.js", { SPELL_TEXTS });

/* ═══ equipment.js ═══ */
const equipRaw = load("Equipment");
const WEAPONS = {};
const ARMOR = {};
const GEAR = {};
const PACKS = {};
for (const e of equipRaw) {
  const cat = e.equipment_category.index;
  if (cat === "weapon") {
    const props = (e.properties || []).map((p) => p.index);
    WEAPONS[e.index] = {
      index: e.index,
      name: e.name,
      category: `${e.weapon_category} ${e.weapon_range}`.toLowerCase(), // "simple melee" etc.
      cost: e.cost ? `${e.cost.quantity} ${e.cost.unit}` : "",
      weight: e.weight ?? 0,
      dmg: e.damage?.damage_dice || null,
      dmgType: e.damage?.damage_type?.index || null,
      versatile: e.two_handed_damage?.damage_dice || null,
      range: e.range || null,
      throwRange: e.throw_range || null,
      props,
    };
  } else if (cat === "armor") {
    ARMOR[e.index] = {
      index: e.index,
      name: e.name,
      category: (e.armor_category || "").toLowerCase(), // light/medium/heavy/shield
      base: e.armor_class?.base ?? 10,
      dexBonus: !!e.armor_class?.dex_bonus,
      dexMax: e.armor_class?.max_bonus ?? null,
      strMin: e.str_minimum || 0,
      stealthDis: !!e.stealth_disadvantage,
      cost: e.cost ? `${e.cost.quantity} ${e.cost.unit}` : "",
      weight: e.weight ?? 0,
    };
  } else if (e.gear_category?.index === "equipment-packs") {
    PACKS[e.index] = {
      index: e.index,
      name: e.name,
      cost: e.cost ? `${e.cost.quantity} ${e.cost.unit}` : "",
      contents: (e.contents || []).map((x) => ({ item: x.item.index, name: x.item.name, qty: x.quantity })),
    };
  } else {
    GEAR[e.index] = {
      index: e.index,
      name: e.name,
      category: e.gear_category?.index || e.tool_category || e.vehicle_category || cat,
      cost: e.cost ? `${e.cost.quantity} ${e.cost.unit}` : "",
      weight: e.weight ?? 0,
    };
  }
}
emit("equipment.js", { WEAPONS, ARMOR, GEAR, PACKS });

/* ═══ backgrounds.js ═══ */
const bgRaw = load("Backgrounds");
const BACKGROUNDS = {};
for (const b of bgRaw) {
  const buckets = profBuckets(b.starting_proficiencies);
  BACKGROUNDS[b.index] = {
    index: b.index,
    name: b.name,
    skills: buckets.skills,
    tools: buckets.tools,
    languages: b.language_options ? { choose: b.language_options.choose } : null,
    feature: b.feature ? { name: b.feature.name, desc: (b.feature.desc || []).join("\n\n") } : null,
    suggestions: {
      traits: (b.personality_traits?.from?.options || []).map((o) => o.string),
      ideals: (b.ideals?.from?.options || []).map((o) => o.desc),
      bonds: (b.bonds?.from?.options || []).map((o) => o.string),
      flaws: (b.flaws?.from?.options || []).map((o) => o.string),
    },
  };
}
emit("backgrounds.js", { BACKGROUNDS });

/* ═══ feats.js (SRD has exactly one: Grappler) ═══ */
const featsRaw = load("Feats");
emit("feats.js", {
  FEATS: Object.fromEntries(
    featsRaw.map((f) => [
      f.index,
      {
        index: f.index,
        name: f.name,
        desc: (f.desc || []).join("\n\n"),
        prereqs: (f.prerequisites || []).map((p) => `${p.ability_score?.name || ""} ${p.minimum_score}+`),
      },
    ])
  ),
});

console.log("Done.");
